version: '2'
services:
    blog-app:
        image: blog
        external_links:
            - blog-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10
        ports:
            - 8080:8080
    blog-mysql:
        container_name: blog-mysql
        image: hypriot/rpi-mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=blog
        command: mysqld --lower_case_table_names=1 --skip-ssl
    


